[33mWARNING [0m urllib3.connectionpool:connectionpool.py:874 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000020E50B55460>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/123a871b3365e7506b092a6b74d1d6c6
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:874 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000020E50B75820>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/123a871b3365e7506b092a6b74d1d6c6
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:874 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000020E50B75F70>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/123a871b3365e7506b092a6b74d1d6c6