[33mWARNING [0m urllib3.connectionpool:connectionpool.py:874 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000020E50B74E90>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/e4997eb53f77d421c12bcbac67884eb3
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:874 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000020E50B75070>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/e4997eb53f77d421c12bcbac67884eb3
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:874 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000020E50B741A0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/e4997eb53f77d421c12bcbac67884eb3