[33mWARNING [0m urllib3.connectionpool:connectionpool.py:874 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000020E50B55310>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/7d6b8216b7bb39175c45e86db22740cb
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:874 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000020E50B54950>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/7d6b8216b7bb39175c45e86db22740cb
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:874 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000020E50B565A0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/7d6b8216b7bb39175c45e86db22740cb