[33mWARNING [0m urllib3.connectionpool:connectionpool.py:874 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000020E50B55310>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/aa1420ee680140b81cbfb61171180dfb
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:874 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000020E50B556D0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/aa1420ee680140b81cbfb61171180dfb
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:874 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000020E50B57CB0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/aa1420ee680140b81cbfb61171180dfb