[33mWARNING [0m urllib3.connectionpool:connectionpool.py:874 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000020E50B752B0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/540c4d0a0541061fc9a543a56de2938c
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:874 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000020E50B74B30>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/540c4d0a0541061fc9a543a56de2938c
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:874 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000020E50B74D40>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/540c4d0a0541061fc9a543a56de2938c