[33mWARNING [0m urllib3.connectionpool:connectionpool.py:874 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000020E50B55C70>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/e9cf04b433536ce82ab616b1061feb8c
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:874 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000020E50B56C60>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/e9cf04b433536ce82ab616b1061feb8c
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:874 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000020E50B56660>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/e9cf04b433536ce82ab616b1061feb8c